name: shopping_shoe_ui
description: A flutter ecommerce mobile app for clients and shoe lovers to shop for tailored favorite shoes.


publish_to: 'none' 


environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2

  side_navigation: ^1.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

assets:
 - assets/images/icons/app_bar/cart.png
 - assets/images/icons/app_bar/sort.png
 - assets/images/icons/app_icon/app_icon.png
 - assets/images/icons/drawer/cart_add.png
 - assets/images/icons/drawer/catalog.png
 - assets/images/icons/drawer/discount.png
 - assets/images/icons/drawer/help.png
 - assets/images/icons/drawer/home.png
 - assets/images/icons/drawer/hot_sale.png
 - assets/images/icons/drawer/new_arrival.png
 - assets/images/icons/drawer/notification.png
 - assets/images/icons/drawer/profile.svg
 - assets/images/icons/drawer/settings.png
  - assets/images/icons/drawer/track_orders.png
  - assets/images/icons/drawer/location.png
  - assets/images/products/1.png
  - assets/images/products/2.png
  - assets/images/products/3.png
  - assets/images/products/4.png
  - assets/images/products/5.png
  - assets/images/products/6.png




  
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 